name: sample build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile-mudlet:
    name: sample build
    runs-on: windows-latest

    steps:
      # Install latest CMake.
      - uses: lukka/get-cmake@latest

      # Restore from cache the previously built ports. If cache-miss, download and build vcpkg (aka "bootstrap vcpkg").
      - name: Restore from cache and install vcpkg
        # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
      # Now that vcpkg is installed, it is being used to run with the desired arguments.
      - run: |
          $VCPKG_ROOT/vcpkg install lua:x64-mingw-dynamic
        shell: bash